server:
  port: 8089

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/monopatin_db

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai
  model: llama-3.1-8b-instant
  temperature: 0.3
